// ELEC2645 games console main file.
// This file sets up the board, shows the intro screens, then hands control to
// the shared menu. Each game keeps its own loop and returns here when it exits.

// Custom palette guide used by the shared screens and games.
// 0  = black      
// 1  = white       
// 2  = baby blue    
// 3  = brown     
// 4  = camel tan   
// 5  = camel nose 
// 6  = pale cream  
// 7  = light pink   
// 8  = lavender     
// 9  = grey         
// 10 = sage green   
// 11 = red
// 12 = green
// 13 = blue
// 14 = yellow
// 15 = orange

// STM32 HAL headers generated by STM32CubeMX.
#include "main.h"
#include "tim.h"       // Timers for buzzer, PWM, and periodic ticks.
#include "usart.h"     // Serial output for printf debugging.
#include "gpio.h"      // GPIO pins for buttons and LEDs.
#include "adc.h"       // ADC readings from the joystick.
#include "rng.h"       // Random numbers if a game needs them.




// STM32 clock setup functions.
void SystemClock_Config(void);
void PeriphCommonClock_Config(void);

// Project hardware helpers.
#include "Buzzer.h"    // Buzzer tones.
#include "PWM.h"       // PWM output for the LCD backlight.
#include "LCD.h"       // LCD display driver.
#include "Joystick.h"  // Joystick direction reading.
#include "Utils.h"     // Common utility types.

// Shared menu and input code.
#include "Menu.h"      // Main game menu.
#include "InputHandler.h" // BT2/BT3 press handling.
#include "IntroScreens.h" // Startup pixel art screens.

#include <stdint.h>
#include <stdio.h>
#include <math.h>

// Game entry points. Each game returns the menu state to go to next.
MenuState Game1_Run(void);
MenuState Game2_Run(void);
MenuState Game3_Run(void);

// Buzzer uses TIM2 Channel 3 on this breadboard setup.
Buzzer_cfg_t buzzer_cfg = {
    .htim = &htim2,
    .channel = TIM_CHANNEL_3,
    .tick_freq_hz = 1000000,  // 1 MHz timer clock.
    .min_freq_hz = 20,
    .max_freq_hz = 20000,
    .setup_done = 0
};

// LCD wiring.
ST7789V2_cfg_t cfg0 = {
    .setup_done = 0,
    .spi = SPI2,
    .RST = {.port = GPIOB, .pin = GPIO_PIN_2},
    .BL = {.port = GPIOB, .pin = GPIO_PIN_1},
    .DC = {.port = GPIOB, .pin = GPIO_PIN_11},
    .CS = {.port = GPIOB, .pin = GPIO_PIN_12},
    .MOSI = {.port = GPIOB, .pin = GPIO_PIN_15},
    .SCLK = {.port = GPIOB, .pin = GPIO_PIN_13},
    .dma = {.instance = DMA1, .channel = DMA1_Channel5}
};

// Joystick ADC wiring.
Joystick_cfg_t joystick_cfg = {
    .adc = &hadc1,
    .x_channel = ADC_CHANNEL_1, // A5 on the Nucleo board.
    .y_channel = ADC_CHANNEL_2, // A4 on the Nucleo board.
    .sampling_time = ADC_SAMPLETIME_47CYCLES_5,
    .center_x = JOYSTICK_DEFAULT_CENTER_X,
    .center_y = JOYSTICK_DEFAULT_CENTER_Y,
    .deadzone = JOYSTICK_DEADZONE,
    .setup_done = 0
};

// Latest joystick reading.
Joystick_t joystick_data;

// PWM output used for the LCD backlight.
PWM_cfg_t pwm_cfg = {
    .htim = &htim4,
    .channel = TIM_CHANNEL_1,
    .tick_freq_hz = 1000000,  // 1 MHz timer clock.
    .min_freq_hz = 10,
    .max_freq_hz = 50000,
    .setup_done = 0
};

// Shared menu state.
MenuSystem menu;

// Optional tick counters for games that want timed events.
volatile uint32_t g_tim6_ticks = 0;
volatile uint32_t g_tim7_ticks = 0;

// Button debounce delay used by the input handler.
#define DEBOUNCE_DELAY 200  // ms

// Timer notes for the project:
// TIM2 drives the buzzer, TIM4 is used for PWM, TIM6 gives a 10 ms tick, and
// TIM7 is available as a slower 1 second tick if a game needs it.

/**
 * @brief Send printf output over UART for debugging.
 */
int _write(int file, char *ptr, int len) {
    HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, HAL_MAX_DELAY);
    return len;
}

/**
 * @brief HAL callback for external button interrupts.
 * 
 * The actual button logic is in InputHandler.c so the menu and games can share
 * one clean input state.
 */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin);  // Implemented in InputHandler.c.

/**
 * @brief HAL callback for timer period elapsed interrupts
 *
 * TIM6/TIM7 periodic interrupts are counted here.
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
  if (htim->Instance == TIM6) {
    g_tim6_ticks++;
  }
  else if (htim->Instance == TIM7) {
    g_tim7_ticks++;
  }
}

static void Play_Intro_Tone(Buzzer_Note_t note, uint32_t duration_ms)
{
    buzzer_note(&buzzer_cfg, note, 12);
    HAL_Delay(duration_ms);
    buzzer_off(&buzzer_cfg);
    HAL_Delay(35);
}

static void Play_Intro_Tune(void)
{
    Play_Intro_Tone(NOTE_E5, 90);
    Play_Intro_Tone(NOTE_G5, 90);
    Play_Intro_Tone(NOTE_A5, 120);
    Play_Intro_Tone(NOTE_E5, 160);
}

void Show_Studio_Splash(void)
{
    LCD_Fill_Buffer(2);
    LCD_Draw_Sprite(0, 20, INTRO_SCREEN_HEIGHT, INTRO_SCREEN_WIDTH, intro_studio_sprite);
    LCD_Refresh(&cfg0);
    Play_Intro_Tune();
    HAL_Delay(1150);
}


void Show_Title_Screen(void)
{
    LCD_Fill_Buffer(2);
    LCD_Draw_Sprite(0, 20, INTRO_SCREEN_HEIGHT, INTRO_SCREEN_WIDTH, intro_title_sprite);
    LCD_Refresh(&cfg0);
    HAL_Delay(1800);
}

static void LED1_Set(uint8_t r, uint8_t g, uint8_t b)
{
    // LED1 wiring: PA9=green, PC7=blue, PC8=red.
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_8, r ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, g ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_7, b ? GPIO_PIN_SET : GPIO_PIN_RESET);

    // LED2 wiring: PC9=red, PD2=green, PA5=blue.
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_9, r ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIOD, GPIO_PIN_2, g ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, b ? GPIO_PIN_SET : GPIO_PIN_RESET);
}



/**
  * @brief Main program setup and menu loop.
  * @retval int
  */
int main(void)
{
    /* Basic MCU setup. */
    HAL_Init();
    SystemClock_Config();
    PeriphCommonClock_Config();

    /* Start the board peripherals. */
    MX_GPIO_Init();
    LED1_Set(1, 1, 1);

    MX_USART2_UART_Init();
    MX_ADC1_Init();  // Joystick ADC.
    MX_RNG_Init();   // Random numbers for game logic.
    
    // Set up the LCD before anything tries to draw.
    LCD_init(&cfg0);

    // Start with the shared palette; individual screens can switch palette later.
    LCD_Set_Palette(PALETTE_CUSTOM);

    // Set up the buzzer timer.
    MX_TIM2_Init();
    buzzer_init(&buzzer_cfg);

    // TIM4 is initialized after the LCD to avoid the PB6 setup conflict.
    MX_TIM4_Init();
    
    // General-purpose timers available to the games.
    MX_TIM6_Init();
    MX_TIM7_Init();

    // Keep a 10 ms tick running for any game that needs timing.
    HAL_TIM_Base_Start_IT(&htim6);

    // TIM7 is left off unless a game needs a slower timer.
    // HAL_TIM_Base_Start_IT(&htim7);
  
    // Shared BT2/BT3 input handling.
    Input_Init();
    
    // Joystick input setup.
    Joystick_Init(&joystick_cfg);
    
    // Start from a blank screen before showing the intro art.
    LCD_Fill_Buffer(0);
    LCD_Refresh(&cfg0);

    // Shared startup screens before the menu opens.
    Show_Studio_Splash();
    Show_Title_Screen();
        
    // Backlight PWM.
    PWM_Init(&pwm_cfg);
    PWM_SetFreq(&pwm_cfg, 1000);
    PWM_SetDuty(&pwm_cfg, 50);  // Start at medium brightness.
    
    // Keep PA5 off until a game explicitly uses it.
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);

  


    // Open on the shared menu.
    Menu_Init(&menu);
    
    printf("Menu system initialized. Press BT3 to select.\n");

    // Each screen owns its own loop, then returns the next state here.
    MenuState current_state = MENU_STATE_HOME;
    
    while (1)
    {
        switch (current_state) {
            case MENU_STATE_HOME:
                // Menu returns the game the player selected.
                current_state = Menu_Run(&menu);
                break;
                
            case MENU_STATE_GAME_1:
                // Game 1 returns when the player exits to the menu.
                current_state = Game1_Run();
                break;
                
            case MENU_STATE_GAME_2:
                // Game 2 returns when the player exits to the menu.
                current_state = Game2_Run();
                break;
                
            case MENU_STATE_GAME_3:
                // Spare template slot.
                current_state = Game3_Run();
                break;
                
            default:
                // If the state ever becomes invalid, recover to the menu.
                current_state = MENU_STATE_HOME;
                break;
        }
    }
    
    return 0;
}


// Game code lives in:
//   - game_1/Game_1.c
//   - game_2/Game_2.c  
//   - game_3/Game_3.c
//
// Game 1 and Game 2 are the playable games in the final menu. The shared folder
// keeps the menu and input code in one place.





// STM32CubeMX generated setup functions below.


/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  if (HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 1;
  RCC_OscInitStruct.PLL.PLLN = 10;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief Peripherals Common Clock Configuration
  * @retval None
  */
void PeriphCommonClock_Config(void)
{
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

  /** Initializes the peripherals clock
  */
  PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_RNG|RCC_PERIPHCLK_ADC;
  PeriphClkInit.AdcClockSelection = RCC_ADCCLKSOURCE_PLLSAI1;
  PeriphClkInit.RngClockSelection = RCC_RNGCLKSOURCE_PLLSAI1;
  PeriphClkInit.PLLSAI1.PLLSAI1Source = RCC_PLLSOURCE_HSI;
  PeriphClkInit.PLLSAI1.PLLSAI1M = 1;
  PeriphClkInit.PLLSAI1.PLLSAI1N = 8;
  PeriphClkInit.PLLSAI1.PLLSAI1P = RCC_PLLP_DIV7;
  PeriphClkInit.PLLSAI1.PLLSAI1Q = RCC_PLLQ_DIV4;
  PeriphClkInit.PLLSAI1.PLLSAI1R = RCC_PLLR_DIV2;
  PeriphClkInit.PLLSAI1.PLLSAI1ClockOut = RCC_PLLSAI1_48M2CLK|RCC_PLLSAI1_ADC1CLK;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
  {
    Error_Handler();
  }
}



/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
